# Generated by Django 2.2.5 on 2019-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyorenc',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comentarios'),
        ),
    ]
