# Generated by Django 2.2.5 on 2019-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0002_auto_20191011_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyordet',
            name='imagen1',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media/pic_folder/'),
        ),
        migrations.AlterField(
            model_name='spyordet',
            name='imagen2',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media/pic_folder/'),
        ),
    ]
