# Generated by Django 2.2.5 on 2019-10-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0003_auto_20191014_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyordet',
            name='imagen1',
            field=models.ImageField(default='None/no-img.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='spyordet',
            name='imagen2',
            field=models.ImageField(default='None/no-img.jpg', upload_to='media/'),
        ),
    ]
