# Generated by Django 2.2.5 on 2019-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0004_auto_20191017_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyordet',
            name='imagen1',
            field=models.ImageField(blank=True, default='None/no-img.jpg', null=True, upload_to='media/'),
        ),
    ]
